### ISSUE TITLE
请问中文可以跑通吗

### ISSUE THREAD

**Issue by lijiaoyang** [tyistyler/Bert-Chinese-RE#1]
请问代码可以跑通吗，我看您的中文的train和test是一样的。
另外，想咨询一下您，在  https://github.com/monologg/R-BERT  的基础上做了哪些修改？
感谢！！

**Comment by tyistyler** [comment]
不好意思，现在才注意到您的提问，代码可以跑通，train和test是我在数据集中选择的几个例子。为了方便展示，我设置了train和test是相同的。
跟 https://github.com/monologg/R-BERT 基本一致，只需要修改预训练模型为bert-base-chinese就可以了。
代码有任何问题，我们可以随时交流，我的邮箱是a874214105@163.com
